Build docker image (#4)
* Generate docker image

* Update Makefile

* Expose port

* Update .travis.yml

* Fix lint errors

* Fix build

* Update .travis.yml

* liveness and readiness probes

* Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,7 +2,13 @@ language: go
 
 go:
   - 1.11.x
-  
+
+os:
+  - linux
+  - linux-ppc64le
+services:
+  - docker
+
 # Only build on master, stable branches and tag
 # The stable branch and tag should be leading with numbers
 branches:
@@ -12,5 +18,35 @@ branches:
     - /^v[0-9]+\..*$/
     - /^release-[0-9]+\..*$/
 
+before_install:
+  - source travis-env.sh
+
+install:
+  - make deps
+
 script:
-  - echo "no tests yet!"
+  - echo "TODO no tests yet!"
+  - make lint test build image
+
+# after_success:
+#   - make push
+
+deploy:
+  skip_cleanup: true
+  provider: script
+  script: make docker-login release
+
+after_deploy:
+  - |
+      curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
+      python travis_after_all.py https://travis.ibm.com/api
+      export $(cat .to_export_back)
+      if [[ "$BUILD_LEADER" == "YES" ]]; then
+        if [[ "$BUILD_AGGREGATE_STATUS" == "others_succeeded" ]]; then
+          echo "All jobs succeeded! Creating multi arch image..."
+          make manifest-tool multi-arch
+        else
+          echo "Some jobs failed" && exit 1
+        fi
+      fi
+
